gacutil -i DevExpress.Charts.Designer.v18.1.resources.dll
gacutil -i DevExpress.Dashboard.v18.1.Core.resources.dll
gacutil -i DevExpress.Dashboard.v18.1.Web.resources.dll
gacutil -i DevExpress.Dashboard.v18.1.Win.resources.dll
gacutil -i DevExpress.Data.v18.1.resources.dll
gacutil -i DevExpress.DataAccess.v18.1.resources.dll
gacutil -i DevExpress.DataAccess.v18.1.UI.resources.dll
gacutil -i DevExpress.Diagram.v18.1.Core.resources.dll
gacutil -i DevExpress.Dialogs.v18.1.Core.resources.dll
gacutil -i DevExpress.ExpressApp.AuditTrail.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Dashboards.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Dashboards.Web.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Dashboards.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.FileAttachment.Web.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.FileAttachment.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.HtmlPropertyEditor.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Kpi.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Mobile.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Notifications.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Notifications.Web.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Objects.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Office.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.PivotChart.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Reports.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Reports.Web.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Reports.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.ReportsV2.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.ReportsV2.Web.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.ReportsV2.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Scheduler.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Scheduler.Web.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Scheduler.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Security.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.StateMachine.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Validation.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.ViewVariantsModule.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Web.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Win.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Workflow.v18.1.resources.dll
gacutil -i DevExpress.ExpressApp.Workflow.Win.v18.1.resources.dll
gacutil -i DevExpress.Map.v18.1.Core.resources.dll
gacutil -i DevExpress.Mvvm.v18.1.DataModel.resources.dll
gacutil -i DevExpress.Office.v18.1.Core.resources.dll
gacutil -i DevExpress.Pdf.v18.1.Core.resources.dll
gacutil -i DevExpress.Persistent.Base.v18.1.resources.dll
gacutil -i DevExpress.PivotGrid.v18.1.Core.resources.dll
gacutil -i DevExpress.Printing.v18.1.Core.resources.dll
gacutil -i DevExpress.RichEdit.v18.1.Core.resources.dll
gacutil -i DevExpress.Snap.v18.1.Core.resources.dll
gacutil -i DevExpress.Snap.v18.1.Extensions.resources.dll
gacutil -i DevExpress.Snap.v18.1.resources.dll
gacutil -i DevExpress.Sparkline.v18.1.Core.resources.dll
gacutil -i DevExpress.Spreadsheet.v18.1.Core.resources.dll
gacutil -i DevExpress.Utils.v18.1.resources.dll
gacutil -i DevExpress.Utils.v18.1.UI.resources.dll
gacutil -i DevExpress.Web.ASPxHtmlEditor.v18.1.resources.dll
gacutil -i DevExpress.Web.ASPxRichEdit.v18.1.resources.dll
gacutil -i DevExpress.Web.ASPxScheduler.v18.1.resources.dll
gacutil -i DevExpress.Web.ASPxSpellChecker.v18.1.resources.dll
gacutil -i DevExpress.Web.ASPxSpreadsheet.v18.1.resources.dll
gacutil -i DevExpress.Web.ASPxTreeList.v18.1.resources.dll
gacutil -i DevExpress.Web.Resources.v18.1.resources.dll
gacutil -i DevExpress.Web.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Charts.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Controls.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Core.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Docking.v18.1.resources.dll
gacutil -i DevExpress.Xpf.DocumentViewer.v18.1.Core.resources.dll
gacutil -i DevExpress.Xpf.Gauges.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Grid.v18.1.Core.resources.dll
gacutil -i DevExpress.Xpf.LayoutControl.v18.1.resources.dll
gacutil -i DevExpress.Xpf.NavBar.v18.1.resources.dll
gacutil -i DevExpress.Xpf.PdfViewer.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Printing.v18.1.resources.dll
gacutil -i DevExpress.Xpf.PropertyGrid.v18.1.resources.dll
gacutil -i DevExpress.Xpf.ReportDesigner.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Ribbon.v18.1.resources.dll
gacutil -i DevExpress.Xpf.RichEdit.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Scheduler.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Scheduling.v18.1.resources.dll
gacutil -i DevExpress.Xpf.SpellChecker.v18.1.resources.dll
gacutil -i DevExpress.Xpf.Spreadsheet.v18.1.resources.dll
gacutil -i DevExpress.Xpo.v18.1.resources.dll
gacutil -i DevExpress.XtraBars.v18.1.resources.dll
gacutil -i DevExpress.XtraCharts.v18.1.resources.dll
gacutil -i DevExpress.XtraCharts.v18.1.Wizard.resources.dll
gacutil -i DevExpress.XtraEditors.v18.1.resources.dll
gacutil -i DevExpress.XtraGauges.v18.1.Core.resources.dll
gacutil -i DevExpress.XtraGauges.v18.1.Presets.resources.dll
gacutil -i DevExpress.XtraGrid.v18.1.resources.dll
gacutil -i DevExpress.XtraLayout.v18.1.resources.dll
gacutil -i DevExpress.XtraNavBar.v18.1.resources.dll
gacutil -i DevExpress.XtraPdfViewer.v18.1.resources.dll
gacutil -i DevExpress.XtraPivotGrid.v18.1.resources.dll
gacutil -i DevExpress.XtraPrinting.v18.1.resources.dll
gacutil -i DevExpress.XtraReports.v18.1.Extensions.resources.dll
gacutil -i DevExpress.XtraReports.v18.1.resources.dll
gacutil -i DevExpress.XtraReports.v18.1.Web.resources.dll
gacutil -i DevExpress.XtraRichEdit.v18.1.Extensions.resources.dll
gacutil -i DevExpress.XtraRichEdit.v18.1.resources.dll
gacutil -i DevExpress.XtraScheduler.v18.1.Core.resources.dll
gacutil -i DevExpress.XtraScheduler.v18.1.Extensions.resources.dll
gacutil -i DevExpress.XtraScheduler.v18.1.Reporting.resources.dll
gacutil -i DevExpress.XtraScheduler.v18.1.resources.dll
gacutil -i DevExpress.XtraSpellChecker.v18.1.resources.dll
gacutil -i DevExpress.XtraSpreadsheet.v18.1.resources.dll
gacutil -i DevExpress.XtraTreeList.v18.1.resources.dll
gacutil -i DevExpress.XtraVerticalGrid.v18.1.resources.dll
gacutil -i DevExpress.XtraWizard.v18.1.resources.dll
